[package]
name = "json-five-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", optional = true }

[features]
serde = ["dep:serde"]


[dev-dependencies.serde]
version = "*"
features = ["derive"]